"""index opportunities contact_id

Revision ID: 213d0fa97e31
Revises: 4f8274832dc3
Create Date: 2026-09-15 18:42:07.074687

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "213d0fa97e31"
down_revision: str | Sequence[str] | None = "4f8274832dc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_opportunities_contact_id"), "opportunities", ["contact_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_opportunities_contact_id"), table_name="opportunities")
    # ### end Alembic commands ###
