"""create opportunities table

Revision ID: 4f8274832dc3
Revises: 376fcdca5194
Create Date: 2026-09-15 16:25:30.860703

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f8274832dc3"
down_revision: str | Sequence[str] | None = "376fcdca5194"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("value_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "stage",
            sa.Enum("new", "qualified", "poc", "proposal", "negotiation", name="opportunitystage"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.Enum("open", "won", "lost", name="opportunitystatus"), nullable=False
        ),
        sa.Column("expected_close_date", sa.Date(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opportunities")
    # ### end Alembic commands ###
